name = "pyse2024"
license = "MIT"
licenselink = "https://opensource.org/license/mit/"
description = ""
homepage = "https://sudeste.python.org.br/"
tags = ["python", "hugo", "python sudeste"]
features = []
min_version = "0.110.0"

[author]
name = "Regis Tomkiel<me@tomkiel.com.br>"
homepage = "https://tomkiel.com.br"
